### ISSUE TITLE
How to have the exact same setup as a Nixos noob?

### ISSUE THREAD

**Issue by chrollorifat** [atarashiryo/dotfiles#1]
I am new to nixos. I really like your setup and want to have the same on my machine. But I don't know exactly where to put which files. If you have time, could you please give me a detailed instruction? please?

**Comment by rhaps0dians** [comment]
really simple actually.
first you need to use nixos-unstable repo. if you dont use unstable yet, you want to run: `sudo nix-channel --remove nixos` and then `nix-channel --add https://nixos.org/channels/nixos-unstable nixos `
second, you want to use home-manager to use my configuration (hyprland, waybar, etc) by doing `sudo nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager`
you done all that? we need to update our channel to using `sudo nix-channel --update`
okay, now you need to download my dotfiles (and wallpaper if you want) and then change the nixos-config location to your username and your directory (in configuration.nix) to /home/your-name/your-directory/configuration.nix) and then run `nixos-rebuild switch -I nixos-config=/home/your-name/your-directory/configuration.nix`/
